_layouts:
  - &layout-psd1
    [ 18,19,24,25 ]
  - &layout-psd2
    [ 11,12,13,14,17,20,23,26,29,30,31,32 ]
  - &layout-psd3
    [ 0,1,2,3,4,5,6,7,8,9,10,15,16,21,22,27,28,33,34,35,36,37,38,39,40,41,42,43 ]
    
psd_analysis:
  event-variables:
    - AnaEventHeader/centrality_tracks
  axes:
    - { name: AnaEventHeader/centrality_tracks, bin-edges: [0,5,10,15,25,35,45,60,80,100]}
  q-vectors:
    - name: psd1
      _from: &reference-base-detector
        type: channel
        phi: PsdModules/phi
        weight: PsdModules/signal
        norm: m
        corrections:
          - recentering
          #- twist-and-rescale
        qa:
          - {name: PsdModules/phi, nb: 100, lo: -3.1415926, hi: 3.1415926}
          - {name: PsdModules/signal, nb: 100, lo: 0, hi: 100}
      channel-ids: *layout-psd1
    - name: psd2
      _from: *reference-base-detector
      channel-ids: *layout-psd2
    - name: psd3
      _from: *reference-base-detector
      channel-ids: *layout-psd3
    - name: sts_p
      type: track
      phi: RecParticles/phi
      weight: Ones
      norm: m
      corrections:
        - recentering
        - twist-and-rescale
      cuts:
        RecParticles/pid: { equals: 2212 }
        RecParticles/pT: { range: [0, 3] }
        RecParticles/rapidity: { range: [1.02179, 1.42179] }
    - name: sts_pipos
      type: track
      phi: RecParticles/phi
      weight: Ones
      norm: m
      corrections:
        - recentering
        - twist-and-rescale
      cuts:
        RecParticles/pid: { equals: 211 }
        RecParticles/pT: { range: [0, 1.4] }
        RecParticles/rapidity: { range: [2.42179, 2.82179] }
    - name: Q_psi
      type: psi
      phi:  SimEventHeader/psi_RP
      weight: Ones
      norm: m
      
#-----------------------------------------------------------------------------------------

_detectors: &detectors
  - name: psd1
    tags: [ psd ]
  - name: psd2
    tags: [ psd ]
  - name: psd3
    tags: [ psd ]
  - name: sts_p
    tags: [ sts ]
  - name: sts_pipos
    tags: [ sts ]
  - name: Q_psi
    tags: [ psi ]
  
_axes:
  - &centrality
    name: AnaEventHeader_centrality_tracks
    bin-edges: [0,5,10,15,25,35,45,60,80,100]
_components:
  - &sp_components
    [ x1,y1 ]
    
_queries:
  - &query_psd
    tags: { any-in: [psd] }
  - &query_sts
    tags: { any-in: [sts] }
  - &query_psi
    name: { equals: Q_psi }
    
_task_args:
  - &ta_psd
    query: *query_psd
    query-list: *detectors
    #correction-steps: [plain, recentered, twist, rescaled]
    correction-steps: [recentered]
    components: *sp_components
    weight: ones
  #- &ta_psd_plain
    #query: *query_psd
    #query-list: *detectors
    #correction-steps: [plain]
    #components: *sp_components
    #weight: ones
  - &ta_psd_recentered
    query: *query_psd
    query-list: *detectors
    correction-steps: [recentered]
    components: *sp_components
    weight: ones
  #- &ta_psd_twist
    #query: *query_psd
    #query-list: *detectors
    #correction-steps: [twist]
    #components: *sp_components
    #weight: ones
  #- &ta_psd_rescaled
    #query: *query_psd
    #query-list: *detectors
    #correction-steps: [rescaled]
    #components: *sp_components
    #weight: ones
  - &ta_sts
    query: *query_sts
    query-list: *detectors
    correction-steps: [rescaled]
    components: *sp_components
    weight: ones
  - &ta_psi
    query: *query_psi
    query-list: *detectors
    correction-steps: [plain]
    components: *sp_components
    weight: ones
    
_tasks:
  - args: [*ta_psd, *ta_psi ]
    n-samples: 50
    weights-type: reference
    folder: "/Qpsi"
    axes: [ *centrality ]
  #- args: [*ta_psd_plain, *ta_psd_plain ]
    #n-samples: 50
    #weights-type: reference
    #folder: "/QQ"
    #axes: [ *centrality ]
  - args: [*ta_psd_recentered, *ta_psd_recentered ]
    n-samples: 50
    weights-type: reference
    folder: "/QQ"
    axes: [ *centrality ]
  #- args: [*ta_psd_twist, *ta_psd_twist ]
    #n-samples: 50
    #weights-type: reference
    #folder: "/QQ"
    #axes: [ *centrality ]
  #- args: [*ta_psd_rescaled, *ta_psd_rescaled ]
    #n-samples: 50
    #weights-type: reference
    #folder: "/QQ"
    #axes: [ *centrality ]
  - args: [*ta_psd_recentered, *ta_sts ]
    n-samples: 50
    weights-type: reference
    folder: "/QQ"
    axes: [ *centrality ]
  - args: [*ta_sts, *ta_psd_recentered ]
    n-samples: 50
    weights-type: reference
    folder: "/QQ"
    axes: [ *centrality ]
    